### ISSUE TITLE
Wrong injector for formly generated components after navigation

### ISSUE THREAD

**Issue by chrisbinnefeld** [formly-js/ngx-formly#1240]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
In our application we are extending some of the formly types. While updating to the 5.0.0-beta we discovered a bug within the creation of the components. 

We created a Stackblitz which demonstrates the encountered bug:  
https://formly-dependency-injection-error.stackblitz.io/

To reproduce the bug we need two lazy loaded modules which both provide a different value for the same token.

In `PageModule` we provide `{ provide: 'page', useValue: 'page-one' }` and in `PageTwoModule` `{ provide: 'page', useValue: 'page-two' }`

On the first navigation of page-one we are seeing the expected results.

![image](https://user-images.githubusercontent.com/36038291/47001006-d14aba80-d129-11e8-9de3-8bd89c5f3691.png)

After navigating to page two everything is still right.

![image](https://user-images.githubusercontent.com/36038291/47001025-dad42280-d129-11e8-82d6-cef553bc4109.png)

But after navigating back to page one the wrapper component still gets the value of PageTwo

![image](https://user-images.githubusercontent.com/36038291/47001046-e45d8a80-d129-11e8-8c64-53872a055340.png)

**Expected behavior**
After navigating back to PageOne the wrapper component should get the value of PageOne

**Minimal reproduction of the problem with instructions**
See https://formly-dependency-injection-error.stackblitz.io/

**Research**
We think the problem lies within the FormlyModule. Everytime a FormlyModule is created following lines are executed, which modifies the `FormlyConfig` for every module: 

```
configs.forEach(config => {
      [...(config.types || []), ...(config.wrappers || [])]
      .filter(t => !!t)
      .forEach(t => t.componentFactoryResolver = componentFactoryResolver);

      configService.addConfig(config);
    });
```

**Comment by mohammedzamakhan** [comment]
Why would you not just include formly module in AppModule?

**Comment by chrisbinnefeld** [comment]
If you don't include the `FormlyModule` in a page module (`page.module.ts`) you can't use the formly components (eg. `formly-form`). Besides that, we created a formly type for translation. The translations  are loaded on a per module basis (lazy loading). So we need the right injector in the formly created components in order to translate everything correctly. This worked with ngx-formly < 5.0.0.

**Comment by mohammedzamakhan** [comment]
Will having SharedModule in the application help? https://angular.io/guide/sharing-ngmodules

**Comment by aitboudad** [comment]
didn't have the time the check that issue but I think it's a valid bug that we should fix since it was working before.

**Comment by aitboudad** [comment]
otherwise it must be mentioned in the `UPGRADE` as a breaking change

**Comment by aitboudad** [comment]
fixed in `5.0.0-beta.15`

**Comment by Adam-Michalski** [comment]
@aitboudad is this the same issue or I am doing something wrong

### Describe the bug

When any story is opened for first time is displayed correctly but when I open other story and return to one which was already opened I get error.

```
ERROR Error: NG0205: Injector has already been destroyed.
    at R3Injector.assertNotDestroyed (core.mjs:7986:1)
    at R3Injector.get (core.mjs:7893:1)
    at ChainedInjector.get (core.mjs:12088:1)
    at lookupTokenUsingModuleInjector (core.mjs:3217:1)
    at getOrCreateInjectable (core.mjs:3262:1)
    at NodeInjector.get (core.mjs:3527:1)
    at ViewContainerRef.createComponent (core.mjs:21300:1)
    at FormlyConfig.resolveFieldTypeRef (ngx-formly-core.mjs:411:1)
    at FormlyConfig.getMergedField (ngx-formly-core.mjs:390:1)
    at CoreExtension.initFieldOptions (ngx-formly-core.mjs:2111:1)
```

I have found that some similar issues were solved by angularLegacyRendering: true in preview.js but it does not work for my issue

![image](https://user-images.githubusercontent.com/5684123/226998982-2f77f69d-9fc3-46dd-bb75-dc868c21cc6c.png)

### To Reproduce

https://stackblitz.com/edit/storybook-angular-inline-story-controls-reproduct-w8zp7h

_No response_

### System

```shell
"dependencies": {
    "@angular/animations": "^15.1.0",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
    "@angular/platform-browser": "^15.1.0",
    "@angular/platform-browser-dynamic": "^15.1.0",
    "@angular/router": "^15.1.0",
    "@babel/runtime-corejs3": "^7.21.0",
    "@here/maps-api-for-javascript": "1.37.2",
    "@ngx-formly/bootstrap": "^6.1.1",
    "@ngx-formly/core": "^6.1.1",
    "bootstrap": "^5.2.3",
    "bootstrap-icons": "^1.10.3",
    "bs-stepper": "^1.7.0",
    "country-list-js": "^3.1.7",
    "ngx-bootstrap": "^10.2.0",
    "rxjs": "~7.8.0",
    "simple-element-resize-detector": "^1.3.0",
    "storybook": "^6.5.16",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.1.5",
    "@angular/cli": "~15.1.5",
    "@angular/compiler-cli": "^15.1.0",
    "@babel/core": "^7.20.12",
    "@babel/plugin-transform-runtime": "^7.21.0",
    "@babel/preset-typescript": "^7.21.0",
    "@babel/runtime": "^7.21.0",
    "@compodoc/compodoc": "^1.1.19",
    "@storybook/addon-actions": "^6.5.16",
    "@storybook/addon-essentials": "^6.5.16",
    "@storybook/addon-interactions": "^6.5.16",
    "@storybook/addon-links": "^6.5.16",
    "@storybook/angular": "^6.5.16",
    "@storybook/builder-webpack5": "^6.5.16",
    "@storybook/manager-webpack5": "^6.5.16",
    "@storybook/testing-library": "^0.0.13",
    "@types/country-list-js": "^3.1.2",
    "@types/jasmine": "~4.3.0",
    "@types/simple-element-resize-detector": "^1.3.0",
    "babel-loader": "^8.3.0",
    "copyfiles": "^2.4.1",
    "husky": "^8.0.3",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "lint-staged": "^13.1.2",
    "ng-packagr": "^15.1.0",
    "prettier": "2.8.4",
    "typescript": "~4.9.4"
  }
```


### Additional context

_No response_
